### ISSUE TITLE
Update Cake.ExtendedNuGet to target Cake v3.0.0

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.ExtendedNuGet#139]
[Cake 3.0.0](https://cakebuild.net/blog/2022/11/cake-v3.0.0-released) has been released  🎉

**Comment by nils-a** [comment]
Reminder: The Referenced version of `NuGet.Protocol` for this update should be `6.3.1`.

See https://github.com/cake-build/cake/blob/7728438164e8aa7fef243a8747e0f013d50d3a94/src/Cake.NuGet/Cake.NuGet.csproj#L23
