### ISSUE TITLE
update to newer NuGet.Protocol version to support newer .Net frameworks

### ISSUE THREAD

**Issue by MCCoolMoDAue** [cake-contrib/Cake.ExtendedNuGet#36]
hello,

to support .net 4.8 packages, the NuGet version is too low.
The package depends on NuGet.Protocol 5.0.2, but 5.8.0 is already available.

I cannot use Cake.ExtendedNuGet with a newer Cake.Protocol version, I'Ve tried.

**Comment by augustoproiete** [comment]
This was resolved by #37 which bumps NuGet.Protocol to 5.4.0 and will be available in the next release
