### ISSUE TITLE
Fix CodeQL GitHub workflow

### ISSUE THREAD

**Issue by augustoproiete** [cake-contrib/Cake.ExtendedNuGet#50]
Currently failing: https://github.com/cake-contrib/Cake.ExtendedNuGet/runs/1793233032?check_suite_focus=true

It might be that it's because treating Warning as Errors is on, and if that's true we need to decide to either fix or disable `CCG0005` and `CCG0006` warnings

```bash
Build succeeded.

/.../Cake.ExtendedNuGet/source/Cake.ExtendedNuGet/Cake.ExtendedNuGet.csproj : warning CCG0005: No reference to 'StyleCop.Analyzers' found. Usage of 'StyleCop.Analyzers' is strongly recommended
/.../Cake.ExtendedNuGet/source/Cake.ExtendedNuGet/Cake.ExtendedNuGet.csproj : warning CCG0006: No reference to 'stylecop.json' found. Usage of 'stylecop.json' is strongly recommended.
    2 Warning(s)
    0 Error(s)
```

**Comment by nils-a** [comment]
Weird. The workflow ran fine on the PR, before the merge but not an `develop` after the merge.
I (boldly) re-ran the workflow and the error is gone.
I suggest we close this issue.

**Comment by augustoproiete** [comment]
🤷‍♂️
