### ISSUE TITLE
Update Dependabot-Config so NuGet-references won't update

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.ExtendedNuGet#65]
Discussion started in https://github.com/cake-contrib/Cake.ExtendedNuGet/pull/62#issuecomment-790441650
We should add 
* `NuGet.Protocol`
* `NuGet.Packaging`

in dependabot-ignore, somewhere around here: https://github.com/cake-contrib/Cake.ExtendedNuGet/blob/a54be18cb4660d46fbf18c766e364a82d2c7a493/.github/dependabot.yml#L8-L11

**Comment by nils-a** [comment]
> In fact, I would say it's not only NuGet.Protocol that should be excluded, but any package ID that is referenced by any of the Cake .csproj files (as we know their assemblies will be already loaded in the AppDomain, so by the time the addin tries to load it it's too late)

@augustoproiete for here and now, I suggest limiting to the two above. But I agree, we should find a mechanism to ensure that packages referenced by Cake (in the Cake version that is referenced) are not bumped by dependabot.

**Comment by augustoproiete** [comment]
I pu together the full list of packages: https://github.com/nils-org/dependabot-cake-action/issues/3
