### ISSUE TITLE
Readme should be included in nupkg

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.ExtendedNuGet#91]
The current NuGet.org page looks a bit "empty" without one.

**Comment by mohanhbk** [comment]
Hi 
Could you please elaborate on this issue?

**Comment by nils-a** [comment]
@mohanhbk Sure, assigned to you. Thanks

**Comment by nils-a** [comment]
@mohanhbk sorry, must have been sleeping when I answered. 🤦‍♂️ 
I added a comment on the PR, https://github.com/cake-contrib/Cake.ExtendedNuGet/pull/93#issuecomment-933759641, does that help you?
